name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install tooling
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck shfmt
      - name: Lint and test
        run: |
          make ci
